name: e2e
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.4.0
        with:
          runTests: false
## enable when you have a deployment
#   cypress-e2e-test:
#     #    if you want to enable parallelization
#     # strategy:
#     #   fail-fast: false
#     #   matrix:
#     #     machines: [1]
#     needs: [install-dependencies]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}

#       - name: Install Specific Chrome Version
#         run: |
#           sudo apt-get install -y wget
#           sudo wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#           sudo apt-get install ./google-chrome-stable_current_amd64.deb

#       - name: Cypress e2e tests 🧪
#         uses: cypress-io/github-action@v6.4.0
#         with:
#           browser: chrome
#           config-file: cypress/config/dev.config.ts
#           # if you want to enable parallelization
#           # record: true
#           # parallel: true
#           # group: e2e-tests
#           # tag: e2e-tests
#         env:
#           # if you want to enable parallelization
#           # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
